### ISSUE TITLE
run shutdown.sh in tomcat bin folder will close the container

### ISSUE THREAD

**Issue by carrison** [docker-library/tomcat#102]
how to restart tomcat instance in container?

**Comment by yosifkit** [comment]
Your issue title is the expected behavior (assuming that `shutdown.sh` causes the `catalina.sh` process to exit) since tomcat is the only thing running in the container.  Once it exits the container is stopped.  So the Docker way to restart the items in the container is to just restart (`docker restart`) the container (or a `docker stop` or `docker kill` followed by a `docker start`).
