### ISSUE TITLE
Page Not Accessible from Browser | Tomcat Container in OpenStack VM

### ISSUE THREAD

**Issue by xylene1980** [docker-library/tomcat#117]
i am running tomcat docker container  from my Open stack server. I have mapped <hostport>:<containerport> 9090:8080 and opened ingress for 9090 as well. I am able to curl the  `localhost:9090`  from the open stack server and getting correct response , But when trying to request the webpage from browser i get no response.  Any advise would be of great help

**Comment by yosifkit** [comment]
Sounds like the container is working correctly since you can hit it via `localhost`. I would guess there is firewall or similar in the network between your browser and the VM that is blocking that port.

In the future, since this is not a problem with the image, it'd be better to post questions like this in [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).

**Comment by xylene1980** [comment]
sure @yosifkit thanks
