### ISSUE TITLE
Releases for Java 12 and Java 13

### ISSUE THREAD

**Issue by olliefreeman** [docker-library/tomcat#151]
Hi,

Are there any plans for Java 12 and/or Java 13 releases, and if so what's the likely timescale?

Also is there a particular reason there is no alpine release for Java 11?

**Comment by yosifkit** [comment]
For why no openjdk 11 on Alpine: https://github.com/docker-library/openjdk/issues/272.

On the subject of openjdk 12 and 13, those change to be from `oraclelinux:7-slim` with no Debian version, so there would possibly be a huge shift in the image.

**Comment by olliefreeman** [comment]
thank you

**Comment by tianon** [comment]
I've pushed up a bit of a WIP at https://github.com/docker-library/tomcat/compare/master...infosiftr:oracle (https://github.com/docker-library/tomcat/commit/2c1605d637e0b765fabb57fe42484e53d317df40 is a direct link to the current commit in case the branch ends up going away later).

The biggest TODO there is Tomcat Native support (because I haven't had time or motivation to dig into what packages are necessary to make that work -- help wanted!)

**Comment by qeepcologne** [comment]
i think it was a bad decision to drop alpine image, we had to move to stretch (with very poor and painful java12 support) and now have to shift to oracle linux which is also not the first choice and breaks all the derived images and build process. I think most user prefer ubuntu or centos based image (and for me personally alpine with jdk13ea).

**Comment by tianon** [comment]
JDK 12 and 13 are being added in https://github.com/docker-library/tomcat/pull/164 :+1:
