### ISSUE TITLE
docker images, just want to deploy a war

### ISSUE THREAD

**Issue by f1-outsourcing** [docker-library/tomcat#168]
I just want to deploy a war, as probably most. Should the default page on 8080 not be disabled??

**Comment by wglambert** [comment]
If you want it to 404 then move/delete `/usr/local/tomcat/webapps/ROOT/index.jsp`

You could also ask over at [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repositories are for issues with the image and not necessarily for questions of usability

**Comment by f1-outsourcing** [comment]
yes noticed there was already a debate somewhere about what should be in the docker image. Maybe a solution is to make a dev image. That has then all default stuff of tomcat. 
Now I have (like so many others) create an own image, which is of course a waste of global resources ;)
