### ISSUE TITLE
How long will the tomcat 9 image with openjdk 8 will be maintained?

### ISSUE THREAD

**Issue by aparnavodapalli** [docker-library/tomcat#185]
How long will the tomcat 9 image with openjdk 8 will be maintained? 9.0.30-jdk8-openjdk.
WIll it be updated with latest tomcat 9 and java 8 patches?

**Comment by wglambert** [comment]
I don't see an official EOL date for tomcat 9 or 8.5, but we would parallel that.

From 7 months ago https://lists.apache.org/thread.html/07448b39cb88601272d7f3908d23786ba6e6a052a078f9585ff53360@<dev.tomcat.apache.org>
>There is currently no planned EOL date for 8.5.x.
>We have also stated that we will give at least 12 months notice of the EOL of any release line.

**Comment by yosifkit** [comment]
So, for this `openjdk:8-jdk` based image, it will be as long as both OpenJDK and Tomcat are supported by their respective upstreams. As @wglambert mentions, Tomcat 9 doesn't yet have an EOL. OpenJDK 8 will be as long as the upstream OpenJDK 8 team keeps doing releases and using [adoptopenjdk](https://adoptopenjdk.net/support.html) as a guide, I would guess it should be until "At Least Sep 2023".

Fair warning that the base OS, Debian Stretch is end of regular life in about June 2020, so that may change in the near future (https://wiki.debian.org/DebianReleases). But if we can't change, then the less supported Debian Stretch LTS will still be available until June 2022. See https://wiki.debian.org/LTS for details about the Debian LTS project.
