### ISSUE TITLE
+ command -v yumdb + yum install -y yum-utils /bin/sh: 1: yum: not found

### ISSUE THREAD

**Issue by andro-ajp** [docker-library/tomcat#193]
When using the yum template to build an image, an error was reported and it was unable to continue. Navigate to the Dockerfile and see that it is a process of determining if the yum tool is installed. Since the system itself is already installed, commenting out here will cause subsequent if judgments to be reported.
How should this be resolved?

OS：
CentOS Linux release 7.7.1908 (Core)
Linux jenkins 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Docker version 19.03.8, build afacb8b

**Comment by wglambert** [comment]
`tomcat` doesn't have any variant that uses `yum`

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by tianon** [comment]
It does, but they're all building successfully (they're based on Corretto which is on Amazon Linux); you'll need to provide a bit more detail about what you're trying to do, I think. 😅
