### ISSUE TITLE
How could i can  set JAVA_OPTS in dockerfile?

### ISSUE THREAD

**Issue by Yogurt-lei** [docker-library/tomcat#201]
How could i can  set JAVA_OPTS in dockerfile?

thanks for your reply : )

**Comment by wglambert** [comment]
https://docs.docker.com/engine/reference/builder/#env
https://vsupalov.com/docker-arg-env-variable-guide/#setting-env-values

Questions like these should be asked over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by Yogurt-lei** [comment]
sorry ，my description is not clear，I mean how to set the Java options of catalina.sh in the dockerfile :（，except use `RUN sed -i -e "2iJAVA_OPTS=\"$JAVA_OPTIONS\"" $CATALINA_HOME/bin/catalina.sh`

**Comment by wglambert** [comment]
https://github.com/docker-library/tomcat/issues/8#issuecomment-149728019

**Comment by Yogurt-lei** [comment]
@wglambert 
Thank you for your reply
