### ISSUE TITLE
cloud foundry

### ISSUE THREAD

**Issue by arademaker** [docker-library/tomcat#204]
https://docs.cloudfoundry.org/devguide/deploy-apps/push-docker.html 

Trying to use a container based on the tomcat, `FROM tomcat:8.5`. But it is not working, maybe the missing the `CMD`? Any idea? Does anyone use this container with CF?

**Comment by wglambert** [comment]
You should try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum. And giving all the commands you ran or any relevant files or logs for reproducing the issue would help for troubleshooting
