### ISSUE TITLE
Error since last update 

### ISSUE THREAD

**Issue by fkcrft** [docker-library/tomcat#215]
Hello,

Since the last update on tomcat:9-jdk8-adoptopenjdk-openj9, we encounter the following error "E: Unable to locate package libmysql-java"

Dockerfile
```
FROM tomcat:9-jdk8-adoptopenjdk-openj9
RUN apt-get update && apt-get install git curl libmysql-java -y
```

Output
```
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM tomcat:9-jdk8-adoptopenjdk-openj9
 ---> 46b931f47e17
Step 2/2 : RUN apt-get update && apt-get install git curl libmysql-java -y
 ---> Running in df5429ad826d
Get:1 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
[...]
Get:17 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [4,277 B]
Fetched 16.4 MB in 7s (2,207 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libmysql-java
The command '/bin/sh -c apt-get update && apt-get install git curl libmysql-java -y' returned a non-zero code: 100
```

Do you have an idea, how can i solve this issue ?

**Comment by wglambert** [comment]
This variant is from `adoptopenjdk:8-jdk-openj9` 
https://github.com/docker-library/tomcat/blob/22025622a4fe65a3660132b43a834d703a64e01b/9.0/jdk8/adoptopenjdk-openj9/Dockerfile#L1

Which updated from Ubuntu 18.04 to 20.04 https://github.com/AdoptOpenJDK/openjdk-docker/pull/442, then briefly reverted https://github.com/AdoptOpenJDK/openjdk-docker/pull/447, then back to 20.04 which is what this image is at https://github.com/AdoptOpenJDK/openjdk-docker/pull/455

And the issue you're getting is because `libmysql-java` isn't available for 20.04 https://packages.ubuntu.com/search?keywords=libmysql-java
From what I gather it seems to have been replaced with `libmariadb-java`
