### ISSUE TITLE
docker  container are running but not accessable in browser it showing error 404

### ISSUE THREAD

**Issue by prashanth-1212** [docker-library/tomcat#219]
docker run tomcat is worked only after doing 
docker pull tomcat:latest
docker run -d --name mytomcat -p 8080:8080 tomcat:latest
docker exec -it mytomcat /bin/bash
mv webapps webapps2
mv webapps.dist/ webapps
exit
but  docker run nginx is not working
       docker run hello-world-python is not working 
docker is installed in aws ubuntu ....even docker installed in windows 10  is showing same error
how to fix this?

**Comment by wglambert** [comment]
https://github.com/docker-library/docs/tree/master/tomcat#how-to-use-this-image
>Note: as of docker-library/tomcat#181, the upstream-provided (example) webapps are not enabled by default, per [upstream's security recommendations](https://tomcat.apache.org/tomcat-9.0-doc/security-howto.html#Default_web_applications), but are still available under the `webapps.dist` folder within the image to make them easier to re-enable.

I would try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by stream2stream** [comment]
I've discovered that the script isn't pulling the folders from webapps.dist to webapps/  I cp'ed the files over after a docker run, and it worked.  Looks like there is a step missing int he script
