### ISSUE TITLE
is alpine coming back with jdk16?

### ISSUE THREAD

**Issue by qeepcologne** [docker-library/tomcat#222]
https://openjdk.java.net/jeps/386
ideally as multilayered image with jre only.

**Comment by wglambert** [comment]
When a new OpenJDK version is in Early Access then Alpine is available for testing, and then removed from the Release Candidate as it's not "production-ready because it hasn’t been tested thoroughly enough to be considered GA"

https://github.com/docker-library/openjdk/pull/235#issuecomment-424599754

**Comment by amarkevich** [comment]
[Eclipse Temurin](https://hub.docker.com/_/eclipse-temurin) provide Alpine based images.
Support matrix can be simplified by providing Ubuntu JDK + JRE + Alpine JRE only

**Comment by tianon** [comment]
See #299
