### ISSUE TITLE
Suggested syntax in Dockerfile for $PORT?

### ISSUE THREAD

**Issue by charlesdwright** [docker-library/tomcat#228]
Perhaps the documentation can show an example of how to create a new image allowing for a $PORT environment var using this one.

**Comment by charlesdwright** [comment]
Just curious, what's this?

        <init-param>
          <param-name>expires</param-name>
          <param-value>666</param-value>
        </init-param>

**Comment by wglambert** [comment]
https://github.com/docker-library/tomcat/issues/169#issuecomment-512101112
>it requires modification of XML configuration to change the port -- we currently do not do anything to the default XML configuration provided by Tomcat upstream, and we don't have any plans to do so.

And that snippet looks like an ssl expiry parameter

**Comment by charlesdwright** [comment]
Thank you for responding and helping support the Tomcat image.

Am trying to figure out how to set the port by Env variable.  Are you aware of a tutorial or discussion you can point me to?

Also, the expiry parm just happens to be the Mark of The Beast (666)!

Regards,

C

**Comment by wglambert** [comment]
You would need to provide a modified `server.xml` that can substitute the value for the environment variable
https://stackoverflow.com/a/15556920

It seems unnecessary when you can just have Docker forward whichever port you want to the container (which is listening on port 8080 by default)
https://docs.docker.com/config/containers/container-networking/#published-ports
https://github.com/docker-library/docs/tree/master/tomcat#how-to-use-this-image

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by charlesdwright** [comment]
Agree it does seem unnecessary. But it’s an issue for Heroku which assigns a port at runtime.  

There are workarounds, (ie web runner) but I think solving it will help my  understanding of Docker.

Thank you again and Regards…

C

**Comment by sujiansoft** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
