### ISSUE TITLE
exec: "-network": executable file not found in $PATH: unknown

### ISSUE THREAD

**Issue by chengxingfei83** [docker-library/tomcat#230]
[root@localhost ~]# docker network ls
NETWORK ID     NAME      DRIVER    SCOPE
173ba2712aa8   bridge    bridge    local
a7115b435689   host      host      local
07716ba4ca20   none      null      local
[root@localhost ~]# 
[root@localhost ~]# docker run -d --name lcbm -p 8081:8080 tomcat:8.5.66-jdk8-openjdk --network bridge --network-alias lcbmserver
2a2031b477aed3363dd731a55918ff470c2c9d5430d49eb0632c18e0b8ba1b79
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "--network": executable file not found in $PATH: unknown.
[root@localhost ~]#

**Comment by wglambert** [comment]
See `docker run --help`
```console
Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]
```

You'll also want to `docker network create my-network` to be able to use `--network-alias`
```console
$ docker run -d --name lcbm -p 8081:8080 --network bridge --network-alias lcbmserver tomcat:8.5.66-jdk8-openjdk
docker: network-scoped aliases are only supported for user-defined networks.

$ docker network create my-network
461d3990f45c411913182e0847642714bd4fee8913fc62cbd0642d507a9b1b13

$ docker run -d --name lcbm -p 8081:8080 --network my-network --network-alias lcbmserver tomcat:8.5.66-jdk8-openjdk
0150101ed126db84629f8d7c87febeec8c7aa53cac23df8f11c9d30fd02561fc
```

In the future questions like this should be asked over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
