### ISSUE TITLE
java.lang.NoClassDefFoundError while running examples

### ISSUE THREAD

**Issue by pxc3113** [docker-library/tomcat#244]
How to reproduce the issue:
root@39d189491fd8:/usr/local/tomcat/webapps.dist/examples/WEB-INF/classes/nonblocking# java ByteCounter
Error: Could not find or load main class ByteCounter
Caused by: java.lang.NoClassDefFoundError: nonblocking/ByteCounter (wrong name: ByteCounter)

**Comment by wglambert** [comment]
Your error is `wrong name: ByteCounter` because it's technically `ByteCounter.java`
```console
# ls
'ByteCounter$1.class'                 ByteCounter.java                           NumberWriter.class
'ByteCounter$CounterListener.class'  'NumberWriter$1.class'                      NumberWriter.java
 ByteCounter.class                   'NumberWriter$NumberWriterListener.class'
```

I tested the webapp by moving the folder so it's accessible through the web https://github.com/docker-library/docs/tree/master/tomcat#how-to-use-this-image

![image](https://user-images.githubusercontent.com/26428991/136061518-0eb06a97-4413-42bd-95c3-4e977471fcbd.png)
And the result
![image](https://user-images.githubusercontent.com/26428991/136061543-14355b59-b5fd-4937-93d7-e5c408490a8d.png)


Questions like these are better suited for a dedicated help resource, if you need further help I'd try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
