### ISSUE TITLE
Http call Auto Redirect to https

### ISSUE THREAD

**Issue by avsh1617** [docker-library/tomcat#252]
hello,

We are using tomcat:alpine image in our env and deploying our frontend application. we are using AWS ALB load balancer and it is giving too many redirect error while launching app. it seems tomcat is redirecting this from http to https. to check this we have disable the redirection from ALB end but still http calls are redirecting to https. 

We already tried with the comment out of redirect port configuration in server.xml but it is not working.

Please suggest.

**Comment by tianon** [comment]
Unfortunately, I'd suggest trying a dedicated support forum, such as [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker), or even something Tomcat-specific (since there's nothing inherently "container specific" in the configuration issue you're experiencing).
