### ISSUE TITLE
Why were the Debian+JDK17 images removed in v9.0.63?

### ISSUE THREAD

**Issue by enbwmm** [docker-library/tomcat#262]
Hi, prior to version 9.0.63 we had images based on Debian Buster/Bullseye in combination with JDK17, e.g. _9.0.62-jdk17-openjdk-bullseye_. Commit 3d32b80239bf108ed9fa313d151fe7cd1943f77a removed these variants leaving only Ubuntu based variants with JDK17. Why were these variants removed?

The Debian-based variants with JDK11 are still present, e.g. _9.0.63-jdk11-openjdk-bullseye_. We can't use them, however, due to an issue with cgroups v2 and Kubernetes.

Will the official Debian+JDK17 images be available again or do we have to build our own?

**Comment by wglambert** [comment]
There no longer exist "official" (or even semi-official) vanilla builds of OpenJDK 17 suitable for our use or for publishing as "OpenJDK" (https://jdk.java.net/17/).

**Comment by yosifkit** [comment]
See https://github.com/docker-library/openjdk/pull/495 for where the image was removed from `openjdk`. Since there are no plain builds of openjdk 17 available, then we had no choice but to remove it and users are forced to choose one of the vendor-supplied JDKs.

See also https://github.com/docker-library/docs/pull/2142 and https://github.com/docker-library/tomcat/issues/260.
