### ISSUE TITLE
tomcat:9.0.70-jdk17-temurin failing to build due to CVE-2023-0286

### ISSUE THREAD

**Issue by kevin-denver** [docker-library/tomcat#290]
I am trying to build a docker image using `tomcat:9.0.70-jdk17-temurin` but my secyrity scanner refuses to build the image due to [CVE-2023-0286](https://ubuntu.com/security/CVE-2023-0286). It looks like Ubuntu patched the security issue in jammy (`3.0.2-0ubuntu1.8`) and focal (`1.1.1f-1ubuntu2.17`).

Can you re-release the images including the fix from the OS please?

**Comment by yosifkit** [comment]
Background: 
>Tags in the [official-images] library file[s] are only built through an update to that library file or as a result of its base image being updated (ie, an image `FROM debian:buster` would be rebuilt when `debian:buster` is built). 
>
>\-https://github.com/docker-library/official-images/tree/2f086314307c04e1de77f0a515f20671e60d40bb#library-definition-files

Official Images FAQ:

> Though not every CVE is removed from the images, we take CVEs seriously and try to ensure that images contain the most up-to-date packages available within a reasonable time frame
>
> \- https://github.com/docker-library/faq/tree/0ad5fd60288109c875a54a37f6581b2deaa836db#why-does-my-security-scanner-show-that-an-image-has-cves

Since our build system makes heavy use of Docker build cache, just rebuilding the all of the Dockerfiles won't cause any change. So we rely on periodic base image updates.

> We strive to publish updated images at least monthly for Debian. We also rebuild earlier if there is a critical security need. Many Official Images are maintained by the community or their respective upstream projects, like Ubuntu, Alpine, and Oracle Linux, and are subject to their own maintenance schedule.
>
> \- from the same FAQ link

---

So, as soon as there are [updated Ubuntu images](https://github.com/docker-library/official-images/pulls?q=is%3Apr+label%3Alibrary%2Fubuntu), then the `eclipse-temurin` images and `tomcat` images will be rebuilt.
