### ISSUE TITLE
Provide noble container

### ISSUE THREAD

**Issue by TommyTran732** [docker-library/tomcat#318]
Noble has been out for a few months now. It would be great to have Noble as a base. I scanned jammy with trivy and grype and it seems like there are a lot of known vulnerabilities as this point.

**Comment by LaurentGoderre** [comment]
Eclipse Temurin, on which this image is based on, does not have a noble variant yet.

**Comment by tianon** [comment]
You might also find https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves helpful (ie, grype might not be telling you the full story -- the Ubuntu security team is _extremely_ proactive, even on jammy).

**Comment by TommyTran732** [comment]
@tianon I don't think this should be closed, because the fact of the matter is that there is no noble container yet.

**Comment by tianon** [comment]
Sorry, I should've provided more context -- I've closed this because while we're open to the idea of including a Noble-based image, the prerequisites for us doing so do not currently exist, so I cannot reasonably say that we have any _current_ plans to do so.  Once those prerequisites are met, we will be happy to reconsider/reevalutate.

**Comment by e6c31d** [comment]
@tianon eclipse-temurin now have noble-based images.

**Comment by LaurentGoderre** [comment]
PR created: #319
