### ISSUE TITLE
alpine tomcat

### ISSUE THREAD

**Issue by morro-wind** [docker-library/tomcat#33]
I use alpine build tomcat image
tomcat image file size 130.7Mb
tomcat version 8.5.3

**Comment by yosifkit** [comment]
I think this [comment](https://github.com/docker-library/postgres/pull/119#issuecomment-228834713) is our current response.  ie, we want to be sure that upstream supports running it on Alpine Linux. 

I am especially hesitant with regards to the non-glibc: `musl-libc`, since it has [caused](https://github.com/docker-library/ruby/issues/77) [issues](https://github.com/docker-library/python/issues/112) in the [past](https://github.com/docker-library/python/issues/111).
