### ISSUE TITLE
I want to write a docker file to install apache-tomcat-7.0.64, how can I use this file to acheive that ? 

### ISSUE THREAD

**Issue by LaughingCoffin** [docker-library/tomcat#37]

**Comment by yosifkit** [comment]
I would look in the [`7` directory](https://github.com/docker-library/tomcat/tree/b0cb4ee4d375ade382d77c450903b7c3a0c2b39f/7) and copy the Dockerfile of the variant that you want, whether jre8 or jre7, and whether you want Debian or Alpine.  At that point it should just be changing the `ENV` line with the `TOMCAT_VERSION`.  As far as I know, the `tar.gz` and `asc` files hosted by Apache will still be available, and I think that the gpg keys in the Dockerfile are the same for that version of Tomcat.

That, or you can just `docker pull tomcat:7.0.64`, since the image is still there, but is no longer `supported` so it may not have recent improvements to the image: ie, it does not have Tomcat native installed.

**Comment by LaughingCoffin** [comment]
Thank you for you response, i tried with the given apache-tomcat-7.0.70
version, if they are not that different , then i can make do with this
version as well, also i ran the mysql-5.6 dockerfile which is on a separate
container ,

I want my program's(which is a web application) war file to be deployed in
tomcat's webapp and serve the get or post request , and reflect the changes
in the database of mysql-5.6 which is on a different container.

So far I ran both individually on separate container ,  and now facing
issues with how to populate the database with an existing mysqldump.sql on
boot up. Can you help me with this too ?

**Comment by yosifkit** [comment]
I think the docs on the mysql container are pretty good on this: https://github.com/docker-library/docs/tree/2e0632ea532872574e9b2f78b740606ce81dd8aa/mysql#initializing-a-fresh-instance
```console
$ docker run -d -e MYSQL_ROOT_PASSWORD=... -v /path/to/my.sql:/docker-entrypoint-initdb.d/ mysql
```

**Comment by LaughingCoffin** [comment]
Hi,
Thanks for advice.

Although the approach that i took was different but thanks anyway, I want
to ask one thing though, the docker file which i pulled was based on
ubuntu:trusty which may be working fine because  i too have ubuntu:trusty
OS installed on which i m doing all this, but this is my local computer
server ,

If i push to my private doc-hub or so , and other people pulling this repo
have Cent-OS install instead of ubuntu (which is actually the case) , then
my Dockerfile would not work right ? its build will fail I suppose.

So is there a way to resolve this ? I mean is there a common dockerfile
which can run on different OS (mainly for these two )?

**Comment by yosifkit** [comment]
The base image of the container (CentOS, Debian, Ubuntu) is not really affected by what Linux distribution you are running on the host.  You can run Debian containers on CentOS.
