### ISSUE TITLE
Java-jdk as base for official images - is that possible?

### ISSUE THREAD

**Issue by unix-way** [docker-library/tomcat#38]
Hello guys,

I have recently recently run into an issue: one of my webapps failed to start because it required JDK, while all your official images are based on JRE. I bypassed it by substituting java:7-jre with java:7-jdk in the FROM instruction, but thought it might be worth building official image variants based on JDK instead of JRE, with the corresponding tags, etc. What do you you think of it?

Sincerely yours,
Kirill

**Comment by yosifkit** [comment]
I am going with a -1 on this.  I think the reason is mostly the extra maintenance burden of doubling the number of images (with even more clutter on an already long list in the [dockerfile links section](https://github.com/docker-library/docs/tree/55c5c3d7a30af58ea956c2ffd235e225d2c4474f/tomcat#supported-tags-and-respective-dockerfile-links))

**Comment by md5** [comment]
@yosifkit it seems like it could be helpful to introduce a documentation snippet for Java-based images that gives simple instructions for installing a version-matched JDK in derived images

**Comment by darkwinternight** [comment]
Agree with @md5 -- I also need a JDK.

**Comment by gauravarora** [comment]
I also need a JDK. Its not really possible to use these images for development unless the JDK is used.

**Comment by yosifkit** [comment]
Should we add something like this to the docs, for how to install the jdk at the same version as the jre?
```Dockerfile
FROM tomcat:8-jre8
RUN apt-get update \
	&& apt-get install -y \
		openjdk-8-jdk="$JAVA_DEBIAN_VERSION" \
	&& rm -rf /var/lib/apt/lists/*

# alpine
FROM tomcat:8-jre8-alpine
RUN apk add --no-cache \
	openjdk8="$JAVA_ALPINE_VERSION"
```

**Comment by ashishapy** [comment]
+1 for JDK in official image

**Comment by tianon** [comment]
I'm curious about the use case @unix-way has -- you say your application requires the JDK at runtime?  Can you elaborate on that?

I see the use case for building artifacts from source using the JDK in order to load them into Tomcat, but IMO that should be done in a separate container anyhow (or the JDK installed explicitly).  The JDK-based images are twice the size (~311MB vs ~643MB currently), and so even in the case of building the artifacts, you probably don't want to keep the JDK around at runtime.
