### ISSUE TITLE
lib sqljdbc4.jar not found

### ISSUE THREAD

**Issue by Jayuda** [docker-library/tomcat#51]
Hi,
I have add sqljdbc4.jar to `/usr/local/tomcat/lib` also on my applications at `/webapp/app/WEB-INF/lib` but still error driver not found.
any sugestions ?

**Comment by hishamkaram** [comment]
+1

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant contextual information or files for reproducing the issue

**Comment by wglambert** [comment]
Since this issue doesn't seem to denote any errors with the image I'm going to close

You could also try asking [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
