### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input(…)

### ISSUE THREAD

**Issue by sohaninfo** [docker-library/tomcat#71]
I using following tomcat 8 tag as base image for Dockerfile:
tomcat:8-jre8
OS: Ubuntu 14.04

The deployment is successful. I am deploying Forgerock openam.war file. When I try to access the login page, I see following error:

Uncaught SyntaxError: Unexpected end of JSON input(…)

When I tried same thing in Fedora 25 OS, it worked fine.
I also tried tomcat:8.0-jre8 in Ubuntu:14.04 it also worked fine.

It would be great help if you could give me some pointers/directions to resolve this issue.

**Comment by yosifkit** [comment]
Some of these might be a good starting place: `docker info`. `docker version`, `cat Dockerfile`, `cat docker-compose.yml`, `docker run` command? `docker logs tomcat-container`.

**Comment by wglambert** [comment]
Having been a year without followup information I'm going to prune.

Given that the issue is more of a usability question, it would be more suited for [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
