### ISSUE TITLE
Tomcat 7 with JRE8 - Alphine build error

### ISSUE THREAD

**Issue by frostarun** [docker-library/tomcat#75]
The related docker file is throwing this error 
https://github.com/docker-library/tomcat/blob/5ac222d258dc70c77bb3a9a4fab81ea286c9abd1/7/jre8-alpine/Dockerfile

 **devicemapper: Can't set cookie dm_task_set_cookie failed**

[root@host-10-40-40-134 alpine]# docker build /alpine/
Sending build context to Docker daemon  5.12 kB
Step 1 : FROM openjdk:8-jre-alpine
Trying to pull repository docker.io/library/openjdk ...
8-jre-alpine: Pulling from docker.io/library/openjdk
2aecc7e1714b: Extracting [==================================================>]  1.99 MB/1.99 MB
e7bb7a1c6ee7: Download complete
432e3c96aacd: Download complete
failed to register layer: devmapper: Error activating devmapper device for '23a08152d71a38035b245d4b2549d74036911b8e8ab7c88b0f4399a4668c2839': devicemapper: Can't set cookie dm_task_set_cookie failed

**Comment by tianon** [comment]
This is definitely an issue with your Docker environment configuration -- I'd recommend trying to get off the devicemapper storage driver, but a few better places to get help with environment issues in general would be [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).

Closing since this isn't an issue with this image (I can build it successfully locally, as can the official images build server and Travis CI -- https://travis-ci.org/docker-library/tomcat/builds/242114131). :+1:
