### ISSUE TITLE
404 error when trying to access webapp via tomcat manager

### ISSUE THREAD

**Issue by lvenga** [docker-library/tomcat#90]
I am trying to access my webapp deployed successfully within tomcat 

`docker run -it --rm -p 8888:8080 -v /Users/laura/Desktop/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml:ro  -v /Users/laura/Desktop/glossary.war:/usr/local/tomcat/webapps/glossary.war tomcat:8.0`

Unfortunately I'm getting a 404 when trying to access it: 
![image](https://user-images.githubusercontent.com/8158355/32684085-8a929d4c-c680-11e7-84f3-fcdbc2ae407c.png)
![image](https://user-images.githubusercontent.com/8158355/32684074-7398ec40-c680-11e7-97c1-159666e49841.png)

Any idea what is happening?

**Comment by tianon** [comment]
I think you might have better luck getting help debugging your configuration over on [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker) (since it's not clear whether this is an issue with the image or your configuration as-is).

**Comment by francy328** [comment]
what is the meaning of ro in the command? 
/usr/local/tomcat/conf/tomcat-users.xml:ro

**Comment by tianon** [comment]
In a mount, it means the mount is read-only.
