### ISSUE TITLE
How Can I set a different port other than 8080 ?

### ISSUE THREAD

**Issue by suresh-nataraj** [docker-library/tomcat#91]
I am using $PORT as environment variable and binding it . Is it possible to start the tomcat in the $PORT ?

**Comment by yosifkit** [comment]
We haven't added anything to the image to use an environment variable, so as far as I know it would just be the normal way to change the port tomcat listens on by editing the `conf/server.xml` in the working directory `/usr/local/tomcat`.

One question is why do you need to change it? If you are setting it up for external services or users to connect to it, then `-p hostport:8080` on your `docker run` will allow you to choose any port you want on the host.  You could also setup a reverse proxy like nginx to serve multiple tomcat containers on the same server that each are running on port 8080.

**Comment by delfer** [comment]
@yosifkit 

> One question is why do you need to change it?

For example to start multiply tomcats in single kubernetes pod: containers in pod use single ports namespace.

**Comment by tianon** [comment]
@delfer for that use-case, you'll need to update the configuration inside the image (which is similar to what's going to be required to do the same thing with a lot of other software too)

Since the original question here is solved, I'm going to close.

If you need `tomcat` to support a `PORT` environment variable at runtime, I'd recommend writing yourself a short entrypoint script to make the relevant configuration change during container startup (since I don't believe `conf/server.xml` can reference an environment variable directly).

**Comment by delfer** [comment]
```
#!/bin/bash
if [ -z "$TOMCAT_HTTP_PORT" ]
then 
  echo "Tomcat HTTP port not changed"
else 
  echo "Tomcat HTTP port set to $TOMCAT_HTTP_PORT"
  sed -i "s/port=\"[0-9]\+\" protocol=\"HTTP\/1.1\"/port=\"$TOMCAT_HTTP_PORT\" protocol=\"HTTP\/1.1\"/" $CATALINA_HOME/conf/server.xml
fi

if [ -z "$TOMCAT_AJP_PORT" ]
then 
  echo "Tomcat AJP port not changed"
else 
  echo "Tomcat AJP port set to $TOMCAT_AJP_PORT"
  sed -i "s/port=\"[0-9]\+\" protocol=\"AJP\/1.3\"/port=\"$TOMCAT_AJP_PORT\" protocol=\"AJP\/1.3\"/" $CATALINA_HOME/conf/server.xml
fi

if [ -z "$TOMCAT_SHD_PORT" ]
then 
  echo "Tomcat shutdown port not changed"
else 
  echo "Tomcat shutdown port set to $TOMCAT_SHD_PORT"
  sed -i "s/port=\"[0-9]\+\" shutdown=\"SHUTDOWN\"/port=\"$TOMCAT_SHD_PORT\" shutdown=\"SHUTDOWN\"/" $CATALINA_HOME/conf/server.xml
fi
```
