### ISSUE TITLE
manager's context is limited to access from only localhost, rendering it unusable

### ISSUE THREAD

**Issue by hardyoyo** [docker-library/tomcat#95]
The manager webapp in this container has a valve setting that limits access to only localhost (127.0.0.1), which makes the manager webapp unusable when you attempt to access it from the host. Since this is already an un-hardened Tomcat instance (runs as root), this level of "security" is of dubious value. It should probably be changed. It **should** also be possible to define a [context fragment](https://cas.hgtc.edu/docs/config/context.html#Defining_a_context) to override the default context provided in the manager webpapp config. HOWEVER, from the small amount of tinkering I've done with the "latest" version of this container, it appears that the path `$CATALINA_BASE/conf/[enginename]/[hostname]/` is not created when Tomcat is run, nor is it used if one creates it by hand. This is perplexing, and causes me to wonder if anyone is actually using this container to deploy webapps, and if so, can you please share your work? Thanks!

**Comment by adlerr1** [comment]
to make it happen you have to edit the context.xml files in the subdirectories
<tomcathome>/webapps/manager/META-INF/context.xml
and
<tomcathome>/webapps/host-manager/META-INF/context.xml
by default access is restricted to localhost

comment the localhost restrictions out or change it

**Comment by tianon** [comment]
Closing since this appears resolved (and more of a support question than an issue with the image).

In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).  Thanks!
